stages:
  - build
  - test

build-job:
  stage: build
  tags:
    - linux
  image: gcc
  before_script:
    - apt-get update --yes
    - apt-get install --yes cmake
  script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
  artifacts:
  paths:
    - build

test-job:
  stage: test
  tags:
    - linux
  image: gcc
  before_script:
    - apt-get update --yes
    - apt-get install --yes cmake
  script:
    - cd/build
    - tst/Factorial_test
  dependencies:
    - build-job
